# Generated by Django 5.1.2 on 2024-10-18 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Campaigns',
            new_name='Campaign',
        ),
    ]
